repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies: []
        args: ["--config-file=pyproject.toml"]
        exclude: '(^|/)tests/'

  # Local hooks
  - repo: local
    hooks:
      - id: pytest-fast
        name: pytest (fast subset)
        entry: python -m pytest -q -m "not slow" --maxfail=1
        language: system
        types: [python]
        pass_filenames: false
        stages: [commit]
        # Keep this quick (<10s ideally)
      - id: coverage-xml
        name: Generate coverage xml (on demand)
        entry: python -m pytest -q --cov=scraper/jobminer --cov-report=xml:coverage.xml -m "not slow" --maxfail=1
        language: system
        types: [python]
        pass_filenames: false
        stages: [manual]  # run via: pre-commit run coverage-xml
      - id: pytest-full
        name: pytest full (pre-push)
        entry: python -m pytest -q --maxfail=1
        language: system
        types: [python]
        pass_filenames: false
        stages: [push]